version: '3.8'

services:
  # --- PostgreSQL ---
  postgres:
    image: postgres:15-alpine
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - food-app-network

  # --- Backend (Go) ---
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - food-app-network

  # --- Redis (optional, keep for future cache) ---
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - food-app-network

volumes:
  postgres_data:

networks:
  food-app-network:
    driver: bridge
